### ISSUE TITLE
Use Explain queries (or equivalent) to reduce load on Looker and warehouse

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#107]
Currently, spectacles runs `limit 0` queries for each explore or each dimension. If we could instead use an `explain` of the query, we would be able to limit the load.

Initial feeling is to do this via the SQL runner.

**Comment by joshtemple** [comment]
Closing this as the `limit 0` and `where 1=2` approach is best for now and from our research with query planners, seems to function effectively as an `explain` query.
