### ISSUE TITLE
Fix CircleCI builds to run from external contributors

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#109]

**Comment by iserko** [comment]
This is a simple flag in CircleCI

![Screenshot 2019-11-12 at 08 39 43](https://user-images.githubusercontent.com/473071/68655812-9e3f4a00-0528-11ea-8050-1ea9ff9ee977.png)

**Comment by DylanBaker** [comment]
Thanks @iserko. I think that should now be fixed 👍
