### ISSUE TITLE
Using Fonz against master branch

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#11]
While the initial implementation is/was focused around testing a Looker development branch, typically on a Looker PR. Another use-case is to test the master Looker branch while developing in some other area of the data warehouse. 

Currently, Fonz moves to the development workspace and the checks out whichever branch is passed to it. Unfortunately, this does work for 'master' as you can't check out 'master' during a dev session. 

I think we need to enable a way for Fonz to be run against master. I initially see three possible ways of doing this:

* A different command
* A flag for the run command that tells Fonz not to move into the development workspace (or in fact actively move to 'prod'
* Have a conditional statement that catches the 'master' branch being passed and in those instances ensure Fonz is using 'prod'.

**Comment by joshtemple** [comment]
@DylanBaker, I think the third option you've outlined here is my preferred approach. It simplifies the UX. The user shouldn't have to know we need to turn dev mode on or off or know about workspaces and sessions. The only potential issue I can think of is if someone has a repo where their production branch is not called `master`, but I'm not sure this is even possible in the Looker Git setup.

**Comment by DylanBaker** [comment]
@joshtemple It appears it's not currently possible, but eventually could be: https://discourse.looker.com/t/set-production-branch-to-something-other-than-master/9689/4
