### ISSUE TITLE
Query results incorrectly assigned expired status by Looker API

### ISSUE THREAD

**Issue by joshtemple** [spectacles-ci/spectacles#111]
Looker's async `multi_results` [endpoint](https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/query#get_multiple_async_query_results) occasionally reports the status of a running query as `expired` right before the query completes successfully. This causes spectacles to incorrectly mark the query as errored, when in fact, the query was successful.

In a [previous change](https://github.com/spectacles-ci/spectacles/commit/0b463a11d151ef067f98cc98ddffe6115c7a2e66#diff-cbee2ab0268f8f001868af4ca066ba04L234-R237), we considered marking all `expired` queries as `complete`, but this becomes a problem if a query is killed manually (see report in #104) since it's subsequently marked as `expired`.

We will reach out to Looker to see if we can reproduce and fix the `expired` issue.

**Comment by iserko** [comment]
Just had it happen on our instance:
```
Attempting to get results for 1 query tasks
Query task a607517addb9d3159300ee61d314e40e status is running
Attempting to get results for 1 query tasks
Query task a607517addb9d3159300ee61d314e40e status is expired
Attempting to get results for 1 query tasks
Query task a607517addb9d3159300ee61d314e40e status is error
```
