### ISSUE TITLE
ISSUE - 'unable to get local issuer certificate'

### ISSUE THREAD

**Issue by ibbysyed** [spectacles-ci/spectacles#112]
Hey! Starting trying to integrate this into our workflow at Peloton, got decently far, but then get an ssl certificate error - is there anything on the looker side I'm missing maybe? 

`(jupyter3) isyed-ACLVDR:~ ibrahim.syed$ spectacles sql --config-file yamls/looker_configuration.yaml --project XXXX --branch XXX --explores XXX.XXX
Connected using Looker API 3.1
Looker instance version is 6.22.18
Building LookML project hierarchy for project peloton_XXX

======================== Testing 1 explore [batch mode] ========================

Encountered unexpected ClientConnectorCertificateError: "Cannot connect to host onepeloton.looker.com:19999 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')]"
Full error traceback logged to logs/logs.txt`

**Comment by ibbysyed** [comment]
(I know this is early, just thought I would mess with it :) ) - feel free to ignore if this forum isn't meant for testing. Also, feel free to reach out to me at ibby.syed@onepeloton.com

**Comment by joshtemple** [comment]
Shot in the dark here, but can you try specifying your base URL with `http://` in front?

**Comment by ibbysyed** [comment]
ha - that's what I started off with, but it doesn't actually instantiate the API if I do that. 

`Encountered unexpected ConnectionError: "('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))"`

**Comment by joshtemple** [comment]
Can you try running:
```
pip install "requests[security]"
```
Seems like it's [an issue](https://stackoverflow.com/questions/38853972/python-client-error-connection-reset-by-peer) with outdated SSL in your Python install or virtualenv.

**Comment by ibbysyed** [comment]
When I run it with http://, it fails at session creation, gives me the error: 

`Encountered unexpected ConnectionError: "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"`

with https://, it creates the session and gets to `=====TESTING 1 explore [batch mode]===` and then fails with:

`Encountered unexpected ClientConnectorCertificateError: "Cannot connect to host onepeloton.looker.com:19999 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')]"` 

let me do some digging around for a bit, updating this thread if you guys have any ideas :)

**Comment by joshtemple** [comment]
Are you on a self-hosted or Looker-hosted instance? Are you able to connect to the interactive docs page in your browser if you go to `https://onepeloton.looker.com:19999/api-docs/index.html`?

**Comment by ibbysyed** [comment]
Hey there - 

It's a looker-hosted instance, and yes I can.

**Comment by joshtemple** [comment]
I'm guessing it has something to do with the fact that `aiohttp`, the library we use for async requests, [relies on the Python install to have its own SSL certificates](
https://github.com/aio-libs/aiohttp/issues/2822#issuecomment-372346509).

Could you try following [the steps here](https://timonweb.com/tutorials/fixing-certificate_verify_failed-error-when-trying-requests_html-out-on-mac/) to update your certificates and see if that fixes it?

**Comment by joshtemple** [comment]
@ibbysyed, did you have any luck trying the steps above?

**Comment by ibbysyed** [comment]
Hey @joshtemple sorry - got sidetracked with some other stuff and wasn't able to get it taken care of. I'm going to close out this issue because it looks exactly like what I've got going on.

**Comment by joshtemple** [comment]
Closing this as stale. Please re-open if this is still an issue for you on the latest version of Spectacles!
