### ISSUE TITLE
Suggest using black formatter on the code

### ISSUE THREAD

**Issue by iserko** [spectacles-ci/spectacles#113]
[Black](https://black.readthedocs.io/en/stable/) is an opinionated code formatter for Python projects
[It's use was accepted by the Django framework 5 months ago](https://github.com/django/deps/blob/master/accepted/0008-black.rst) ... I like their foreword :)

The gist of it is ... you let black deal with any formatting questions and no arguments about which comma or new line should go where or when.

As for why you would want this ... when you have external contributors with various different styles, this makes the conversation more on point about what the code is supposed to do and not how it looks.

**Comment by DylanBaker** [comment]
Thanks @iserko. @joshtemple and I have Black enabled on save on our machines. How does this typically work with external contributors? Is it just that we tell them that is the formatting that we insist on, or do we actually have something on Github that amends the code post-commit?

**Comment by iserko** [comment]
@DylanBaker usually the CI runs black and you provide it `--check`, so you just make it part of the linting along flake8. So if a CI build fails for a Pull Request you won't merge it.

From the docs:
```
  --check                         Don't write the files back, just return the
                                  status.  Return code 0 means nothing would
                                  change.  Return code 1 means some files
                                  would be reformatted.  Return code 123 means
                                  there was an internal error.
```

**Comment by iserko** [comment]
@DylanBaker 
![Screenshot 2019-11-12 at 14 39 53](https://user-images.githubusercontent.com/473071/68680892-56d1b180-055a-11ea-96ed-e35c6a51aee7.png)
