### ISSUE TITLE
Looker API token expires after an hour

### ISSUE THREAD

**Issue by iserko** [spectacles-ci/spectacles#114]
I've had a few issues with our explores taking a long time to execute, either due to big PDTs needing to rebuild, or the data set is too big with lots of complex joins.

As soon as we exceed an hour of run time, the API rejects further requests against the multi_queries endpoint saying "Unauthorized".

Just need to rerun `authenticate` if we're still using the client after 30 minutes or so, so that it refreshes the token.

**Comment by bryan-at-looker** [comment]
It’s worth noting that Looker’s new python SDK will automatically log the API back in for this use case. It checks the AccessToken object to verify it’s still valid.

**Comment by DylanBaker** [comment]
Thanks @bryan-at-looker. @joshtemple sounds like per our previous conversation, it's going to be worth moving across to the new SDK.
