### ISSUE TITLE
401 client error

### ISSUE THREAD

**Issue by rjnordeen** [spectacles-ci/spectacles#135]
any reason spectales would connect but fail to run sql?  

```
➜  ~ spectacles connect --config-file ~/looker_config.yml
Connected using Looker API 3.1
➜  ~ spectacles sql --config-file ~/looker_config.yml --project redacted --branch test
Connected using Looker API 3.1
Unable to update session to development workspace.
Looker API error encountered: 401 Client Error: Unauthorized for url: https://redacted.looker.com:19999/api/3.1/session
Message received from Looker's API: "Requires authentication."

```

**Comment by DylanBaker** [comment]
One of the reasons would be if you had passed an incorrect project and/or branch, but that doesn't look like the error here. 

It's failing on changing the user to development mode. Is the account that you are using a developer account?

**Comment by rjnordeen** [comment]
Yes project name is right, and I'm using my account which is a dev account,
when I try passing in my dev branch I get:

Unable to update session to development workspace.

**Comment by DylanBaker** [comment]
@joshtemple do you have any ideas here? I can't figure out why it would require re-authentication here.

As a related aside, should we log all the API calls for easier debugging?

**Comment by rjnordeen** [comment]
Or a debug flag :)

**Comment by DylanBaker** [comment]
Not documented, but you can run with `-v` to see the full logs in your terminal. But we don't log the calls, which would probably be helpful/needed.

**Comment by joshtemple** [comment]
@rjnordeen, can you try running with `--branch master` and see if that works for you? It's really strange that Looker would tell you that your session is unauthenticated when you definitely are (as evidenced by the `Connected using Looker API 3.1` message.

**Comment by rjnordeen** [comment]
Same thing w/  prod space and didnt see much extra running w/ -v

Authenticating Looker API credentials
Connected using Looker API 3.1
Updating session to use production workspace
Unable to update session to production workspace.
Looker API error encountered: 401 Client Error: Unauthorized for url:
Message received from Looker's API: "Requires authentication."

**Comment by joshtemple** [comment]
What happens if you try this? I'm curious to know if it's even possible to do this from the interactive API docs.
1. Go to the API interactive docs page (https://redacted.looker.com:19999/api-docs/index.html)
1. Login with the _same client ID and secret you use for spectacles_
1. Scroll down to the Session section, expand it, and click `update_session`
1. In the `body` section, paste `{"workspace_id": "dev"}`
1. Click the Try it out! button

Do you still get a 401 response?

**Comment by rjnordeen** [comment]
yep that worked - got a 200.


{
  "workspace_id": "dev",
  "sudo_user_id": null,
  "can": {
    "view": true,
    "update": true
  }
}

**Comment by joshtemple** [comment]
Are you able to run this via Python with your spectacles user credentials from your local?
```python
import requests

BASE_URL = "https://redacted.looker.com:19999/api/3.1/"
CLIENT_ID = ""
CLIENT_SECRET = ""

if __name__ == "__main__":
    session = requests.Session()
    response = session.post(
        BASE_URL + "login",
        data={"client_id": CLIENT_ID, "client_secret": CLIENT_SECRET},
    )
    response.raise_for_status()
    access_token = response.json()["access_token"]
    session.headers = {"Authorization": f"token {access_token}"}
    print(f"Authenticated successfully")

    body = {"workspace_id": "dev"}
    response = session.patch(BASE_URL + "session", json=body)
    response.raise_for_status()
    print("Successfully changed to the dev workspace")
```

**Comment by rjnordeen** [comment]
>>> response.raise_for_status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line
940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:
https://redacted.looker.com:19999/api/3.1/session

**Comment by joshtemple** [comment]
That's super interesting. We're wondering if you might not have workspaces with IDs that are `dev` or `production`. Can you try hitting the [Get All Workspaces endpoint](https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/workspace#get_all_workspaces) in the interactive docs and confirm that you do have workspaces with IDs `dev` or `production`?

**Comment by joshtemple** [comment]
Closing this as stale. Please re-open if this is still an issue for you on the latest version of Spectacles!
