### ISSUE TITLE
Add a content validator

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#138]
Spectacles users would benefit from an additional validator that runs Looker's Content Validation via the API. There are a number of open questions about how this should work. This validator could expose the output in two possible ways:

* All content that requires validating on that branch. This would be a simple call to the content validation endpoint.
* All content that requires validating on that branch **that doesn't** require validating on the master branch, i.e. things that this branch actually broke. This would require two calls and comparison of content between the two. 

My gut feel is that we probably want to provide both ways, possibly controlled by a flag.

**Comment by joshtemple** [comment]
Adding some more questions to be answered:

1. What should people be able to select or exclude? Folders? Spaces? Anything in a private space?

2. How should the content be grouped? In Looker you can change this to group on error, folder, or content. Should we provide an option in the CLI to do the same or is this superfluous?
