### ISSUE TITLE
"module 'asyncio' has no attribute 'create_task'"

### ISSUE THREAD

**Issue by ejgolden94** [spectacles-ci/spectacles#149]
Hey! 

We're getting the rest of my team up to speed on running spectacles locally. They all (3 of them) pip installed spectacles yesterday, can successfully connect to the looker api, but when running the SQL validator all get this error:

```
Connected to Looker version 6.24.25 using Looker API 3.1
Checked out branch 
Building LookML project hierarchy for project
======================= Testing 69 explores [batch mode] =======================
Encountered unexpected AttributeError: "module 'asyncio' has no attribute 'create_task'"
Full error traceback logged to logs/logs.txt
```

^^ running SQL validator with config file. On python 3.7. For the two of us who installed spectacles  ~2 weeks ago - and seemingly all else being equal - we get no error.

**Comment by joshtemple** [comment]
Hi @ejgolden94! Double-check the Python version. `create_task` was added in 3.7 so I'm pretty confident the individual encountering this error is running on an earlier version of Python.

What do you get for `python -V` at the command line?

**Comment by ejgolden94** [comment]
that was definitely the issue -- for both of them they had 3.7.5 installed but Anaconda (which is installed on both of their computers but not Akshay or mine) was pointing at 3.6.
