### ISSUE TITLE
Add functionality to exclude specific explores

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#153]
Currently, you can select which explores to test, but there isn't functionality to exclude certain explores. We should add this functionality.

**Comment by joshtemple** [comment]
Should this follow the same syntax with the `--explores` parameter? For example:

* To exclude _all_ explores in the model `thelook`:
```--exclude thelook/*```
* To exclude _only_ the explore `orders_items` in the model `thelook`:
```--exclude thelook/orders_items```
* To exclude _both_ explores `orders_items` and `sessions` in the model `thelook`:
```--exclude thelook.orders_items thelook.sessions```

**Comment by DylanBaker** [comment]
Yeah, that's what I imagine (except for `/` in the last line instead of `.`, which I think is what you meant.)

**Comment by lukeacparsons** [comment]
We're running into the need for this with an explore that's based on a native PDT. The Spectacles run grinds to a halt after adding this explore where the PDT needs to be built. Have you guys handled this use case before?

**Comment by DylanBaker** [comment]
@lukeacparsons We have seen the behaviour of PDTs slowing down Spectacles runs, as Looker has to wait for the PDT to build before it runs the queries. Is that the behaviour you're seeing or is it that you're getting an error on the native PDTs?
