### ISSUE TITLE
Feature Request: ignore hidden: yes columns

### ISSUE THREAD

**Issue by ernestoongaro** [spectacles-ci/spectacles#163]
Just validated a large model with lots of hidden fields that are hidden because they aren't supposed to be used on thier own. I'm aware of `-- spectacles: ignore` and the discussion in #35 but I think there could be a --ignore-hidden that doesn't test hidden columns that kills two birds with one stone

Cheers - thanks for your awesome work!

**Comment by joshtemple** [comment]
I think this is definitely something that would be useful to people. I like the idea of an `--ignore-hidden` flag as well. We'll look to implement something like this!
