### ISSUE TITLE
Allow selecting and excluding content

### ISSUE THREAD

**Issue by joshtemple** [spectacles-ci/spectacles#221]
My first pass at describing this: it should follow the same `--explores` and `--exclude` syntax as the other validators. Here are some potential use cases for selecting or excluding:

- Exclude any content in a personal space
- Select only content associated with a single user
- Select only content associated with a specific model or explore
- Exclude all content associated with a specific model or explore

**Comment by joshtemple** [comment]
`--exclude-personal` excludes all content in personal spaces.

`--excludes` and `--explores` works the same way as it does for other validators, selects and excludes on the basis of models or explores specified.

**Comment by joshtemple** [comment]
@DylanBaker, this is harder than expected.

Looker doesn't return meaningful information about where the content is foldered other than the name of the folder. This means we can't filter out personal folders, not even if we cross-referenced with a list of user names or something (because of sub-folders).

Here's an example:
```
{
    "look": {
    "id": 2,
    "title": "Brand Affinity Stuff",
    "space": {
        "name": "Foobar",
        "id": 25
    },
    "folder": {
        "name": "Foobar",
        "id": 25
    }
}
```

Even including everything in a specific folder won't work because only the parent folder of the content is returned, not a path.

We can still select and exclude based on the LookML model or explore (`--explores` and `--exclude`).

**Comment by DylanBaker** [comment]
@joshtemple I think we could cross references with the list of folders generated from the [get all folders endpoint](https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/folder#get_all_folders). It's less clean, because it's an extra call, but I think would achieve what we wanted here?

**Comment by joshtemple** [comment]
You're exactly right, we can do that with the `is_personal` and `is_personal_descendant` values in that response.
