### ISSUE TITLE
Assert validator should error if no tests are found

### ISSUE THREAD

**Issue by agile** [spectacles-ci/spectacles#227]
Thinking that maybe if we run `assert` and there are no tests that it should result in an error.

Reasoning is because the tests need to be included in a model or view order to be found and run, if they're unwittingly removed then they won't be run and if you're not paying attention you'll still get a nice green build for it.

**Comment by joshtemple** [comment]
I like this idea, Spectacles should error if you're expecting data tests to be run and there are no data tests.
