### ISSUE TITLE
Print Spectacles version in banner

### ISSUE THREAD

**Issue by agile** [spectacles-ci/spectacles#234]
Having the looker version and looker api version being printed is a nice confirmation about the environment being tested and useful output to have.

It would also be nice to see the Spectacles version included in the output as well. Maybe something like this?
> Spectacles 0.2.2 connected to Looker version 7.2.45 using Looker API 3.1

**Comment by joshtemple** [comment]
For this I would recommend using `spectacles --version`, you can add it as a preceding command in CI, for example. Would adding it to the banner give extra value for you?

**Comment by agile** [comment]
> For this I would recommend using `spectacles --version`, you can add it as a preceding command in CI, for example. 

That'll work.

> Would adding it to the banner give extra value for you?

Might just be me but yea I think it's a useful artifact when reviewing logs etc. I'm good with the above suggestion though.

**Comment by joshtemple** [comment]
Cool. I'm going to close this for now, but if other people feel strongly about adding this to the banner, we can consider adding it again. Thanks!
