### ISSUE TITLE
Flaky content errors if models and explores are duplicated across projects

### ISSUE THREAD

**Issue by joshtemple** [spectacles-ci/spectacles#241]
Looker does not return project-qualified errors from the Content Validation endpoint, only model and explore-qualified. This means that if two projects have the same model and explore names (e.g. both have model `ecommerce` with an explore `orders`), we can't associate the errors to the correct project.

This error would be fixed by Looker returning the project name for the error in addition to the model and explore.

**Comment by DylanBaker** [comment]
We have now discovered that model names are globally unique across an instance. This is therefore not a problem.
