### ISSUE TITLE
Lint command to validate project markup.

### ISSUE THREAD

**Issue by agile** [spectacles-ci/spectacles#309]
re: https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/project#validate_project

It'd be very nice to be able to perform the same lint check you can do in the UI by clicking the "Code Validator" button via the CI/CD process.

**Comment by joshtemple** [comment]
I've looked at this before but was unclear what benefit adding this to Spectacles brings since you have to pass this check to commit code in the Looker IDE.

Are you deploying LookML that's not going through that validation step in the IDE?

**Comment by agile** [comment]
Correct, well I do anyway: often creating/editing files and pushing the changes from outside the UI. Others that do tend to work though the UI don't always remember to validate their changes before opening a PR and possibly merging in broken changes. 

I guess the real question is why we don't have that setting better configured, I'll have to follow up with my team mates to figure out if there was some reason we don't have it set to require errors to be fixed.

**Comment by zephschafer** [comment]
I just wanted to +1 this issue as it's something we would like to have as well. 

In response to the comments above. I also just want to note the following:
- We do sometimes commit code from outside the IDE
- Even within the IDE, validation may pass on one project from which the commit is made, but fail on another project for which the given project is a dependency
- Even if committed straightforwardly from the IDE, having the feature from Spectacles would help to confirm that validation succeeds on the branch for a reviewer outside of Looker's IDE

So the lint validation would be quite valuable. (I saw it [noted as coming soon](https://github.com/spectacles-ci/spectacles/blob/master/README.md?plain=1#L18). Is there a timeline for this?)
