### ISSUE TITLE
Long Running SQL Validation

### ISSUE THREAD

**Issue by nicoledavistmx** [spectacles-ci/spectacles#350]
The SQL Validation portion takes ~15 minutes to run in hybrid mode without errors. For example, one explore takes almost 3 minutes. This is concerning as we continue to implement more explores. In order for the pull request process to implement this seamlessly I'd like to know if there is a way to speed up the results.

Result: Completed SQL validation in 2 minutes and 55 seconds.

**Comment by DylanBaker** [comment]
Hi @nicoledavistmx. That's odd. We rarely see those type of run-times. Could you share a few details with me?

It would be good to know the following:
* What warehouse are you on?
* Does it look like the queries are running against the warehouse for that whole time?
* Are you altering the concurrency of the run at all?

**Comment by nicoledavistmx** [comment]
Hi @DylanBaker thanks for the reply
- We are running in Snowflake on a Small warehouse.
- The query looks like it is running against the warehouse for the whole time, based on the Snowflake query history
- The concurrency looks like it is set to 10:
![image](https://user-images.githubusercontent.com/82103135/113933101-2b400e80-97c2-11eb-9005-c14543cd35f4.png)

**Comment by joshtemple** [comment]
Hey @nicoledavistmx! We added a query profiler to Spectacles to help with this sort of thing. It's in our 1.0 release, which isn't officially released yet, but you can install the release candidate and try it out.

To install, run:
```
pip install spectacles==1.0.0rc2
```

The unreleased docs for the profiler are [here](https://deploy-preview-54--affectionate-shaw-852a45.netlify.app/cli/guides/how-to-profile-sql-validation), in a nutshell you add `--profile` and Spectacles will display a list of long running queries. You can tune the cutoff threshold with `--runtime-threshold`.

Let us know what you discover!

As Dylan mentioned, you can also increase the query concurrency with the `--concurrency` argument, which will run more queries in parallel (the default is 10).

**Comment by nicoledavistmx** [comment]
Thank you @joshtemple and @DylanBaker for your responses. We reconfigured the script that runs our pipeline and found that it wasn't running concurrency like it should have. This is running in less than 5 minutes now, which is due to a few long running queries that we have.
