### ISSUE TITLE
Fix Query modes link in the doc

### ISSUE THREAD

**Issue by abudata** [spectacles-ci/spectacles#358]
When clicking on the `choosing a query mode here` in the doc, it shows "Page not found" !
Here is the screenshot.
![image](https://user-images.githubusercontent.com/11818157/116251551-c599cf00-a73c-11eb-8fb9-4ca7078ffab7.png)

**Comment by DylanBaker** [comment]
Thanks @abudata! I've just opened a PR to fix it and we'll merge it in shortly.
