### ISSUE TITLE
Add explore URL to data test results

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#372]
Currently all the data test generates is the name of the failing tests and the test result. Ideally, you would be able to click through to an explore query from the results to see the errors in more detail.

The URL field params come in the GET all LookML tests response and we can create the URL from there.

**Acceptance Criteria**

- [x] Data output from assert validator includes new field `explore_url`.
- [x] CLI prints out explore url as part of assert validation

**Comment by Hawk94** [comment]
https://github.com/spectacles-ci/spectacles/pull/391

**Comment by joshtemple** [comment]
@DylanBaker we don't print out the explore URL for SQL errors. Seeing as it's a quite long URL, do you think it's worth printing for either SQL or assert errors?
