### ISSUE TITLE
Add assert and content validator changes to web application

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#375]
Once the three dependent issues are closed, we should add all that functionality to the web application.

**Acceptance Tests**

- [ ] Content validation suite config has options for folders to include and exclude (design coming)
- [ ] API passes included and excluded folders to the runner
- [ ] Content validation in run details page includes tile name when relevant (design coming)
- [ ] Assert validation in run details page includes link to LookML query

**Comment by joshtemple** [comment]
Issue moved to [spectacles-ci/spectacles-ui #520](https://github.com/spectacles-ci/spectacles-ui/issues/520) via [**ZenHub**](https://www.zenhub.com/)
