### ISSUE TITLE
Spectacles should retry errors that might be transient

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#379]
Semi-regularly Looker seems to return transient 4xx and 5xx errors (particularly often around git branch operations). While we do handle the exceptions gracefully, it is likely worthwhile to try those requests a few times before having the entire run fail. 

Open question as to whether this should be specific API calls or all API calls.

**Comment by joshtemple** [comment]
I believe most of our methods in `client.py` use exponential backoff, but only for Timeout exceptions. Resolving this would be as simple as adding 4xx and 5xx to the list of exceptions that would be retried.

There are, of course, times where 4xx is totally legitimate (like bad auth), so I wouldn't want to retry too many times, but happy to throw an additional retry in if it helps with this.
