### ISSUE TITLE
When API authentication is refreshed after one hour, we lose workspace state

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#392]
After 60 minutes, Looker API creds expire and we refresh them. However, when we refresh the credentials, we end up back in the `production` workspace. Therefore, if the run is testing a branch or commit (1) we start running queries in the wrong workspace and (2) we can't reset the branch successfully at the end of the run. 

When we refresh the credentials, we should be workspace aware and reset to the right workspace.

**Comment by joshtemple** [comment]
I think the answer here is to have the `LookerClient.request` method save the branch/workspace state if it detects that the access token has expired and pass it back into the authenticate method.

Then the authenticate method, after logging back in with the credentials, can restore the branch state. It seems like a straightforward fix.

**Comment by tmastny** [comment]
Does this impact the the CLI? I'm having issues with the `--branch` flag not working and I'm wondering if it's the same issue. Thanks!

**Comment by DylanBaker** [comment]
It would likely affect the CLI if your runs were lasting more than an hour. What's the behaviour you're seeing?

**Comment by tmastny** [comment]
Spectacles found a bug in production (on master) so I created a branch `spectacle-fixes` to fix the issue. However, when running this:
```
spectacles sql --branch spectacle-fixes --explores 'core/*'
```
the error still occurred.

When I merged `spectacle-fixes` into master and ran 
```
spectacles sql --explores 'core/*'
```
the errors were resolved.

My runs were only lasting 2 minutes though, so it must be a different issue (maybe user error?).

**Comment by DylanBaker** [comment]
I think this is an issue with the git state of the user you might have used to run the tests. Users often don't have the most recent code by default. The way to pull it down is to use the `--remote-reset` flag. https://docs.spectacles.dev/cli/reference/sql-validator#remote-reset

We don't do this by default because it can overwrite existing code if the user has outstanding changes. When using a dedicated user for Spectacles, we recommend always using that flag.

**Comment by tmastny** [comment]
Thank you that appeared to be the issue! Sorry for interrupting the thread
