### ISSUE TITLE
Add a LookML validator

### ISSUE THREAD

**Issue by joshtemple** [spectacles-ci/spectacles#413]
In some cases, a Looker user may commit LookML and request Spectacles validation for LookML that was not written in Looker's web IDE. In these cases, the ability to run LookML validation via Spectacles would be helpful because it would catch syntax errors that can cause confusing errors in other validators (like the SQL validator).

We should add a new validator, like `spectacles syntax`, or similar, that runs Looker's LookML validator via the API and returns the results.

**Comment by TimStrietzel** [comment]
Dropping in: I can confirm, that this problem can arise in real-world-scenarios where a user pull the code locally to perform e.g. many file / folder structure based operations and/or 'heavy copy-pasting' between different files. 

In cases like this, a user might prefer the power of a good local text editor over the brower based Looker web IDE UI.

Looking forward to get the fix to this live in Spectacles :-)
