### ISSUE TITLE
SQL test creates invalid code

### ISSUE THREAD

**Issue by leoch20** [spectacles-ci/spectacles#452]
The below dimension fails the SQL test with this error (using snowflake):
```
The Snowflake database encountered an error while running this query. SQL
--
203 | compilation error: Function DATE_TRUNC does not support VARCHAR(16777216)
204 | argument type
```

```yml
 dimension_group: month_time {
    type: time
    timeframes: [
      time,
      date,
    ]
    label: "date"
    group_label: ""
    sql: case
          when ${country} in ('US', 'CA', 'MX') then ${h.created_at}
          else null
        end ;;
  }
```

The sql test tries to run this query to validated the column's datatype, but having `DATA_TRUNC` around `TO_CHAR` produces the db error

```sql
select 
  TO_CHAR(DATE_TRUNC('second', case
      when (c."COUNTRY") in ('US', 'CA', 'MX') then (TO_CHAR(TO_DATE(h."CREATED_AT" ), 'YYYY-MM-DD'))
      else null
    end), 'YYYY-MM-DD HH24:MI:SS') AS "f.month_time",
...
```

This query below reproduces the same error
```sql
select DATE_TRUNC('second', TO_CHAR(TO_DATE(current_timestamp()), 'YYYY-MM-DD'))
```

This can be solved by removing the `TO_CHAR()` function.  Are these datatype conversions added by Spectacles?

**Comment by DylanBaker** [comment]
HI @leoch20. Would you mind sharing the LookML for the `${h.created_at}` dimension? I expect that you've got that as a date, which is what is causing it to use the `to_char` function. 

Spectacles doesn't alter the SQL that Looker generates in any way.

**Comment by leoch20** [comment]
The dimension above calls `${h.created_time}` instead of `${h.created_at}` (my bad).
Here is the `${h.created_time}` dimension:

```yml
view: h {
  sql_table_name: "schema"."table_name"
    ;;
 dimension_group: created {
    type: time
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}."CREATED_AT" ;;
  }
...
}
```

**Comment by DylanBaker** [comment]
I think if you're going to reference a dimension_group field downstream, you're going to want to use the `_raw` version of it. I believe everything else will be turned into a string. Would you mind trying that?

**Comment by leoch20** [comment]
@DylanBaker Thanks that worked. I still need to make sure that no dashboards changed, but that will not be till next week.
