### ISSUE TITLE
Only test dimensions that are changed

### ISSUE THREAD

**Issue by joshtemple** [spectacles-ci/spectacles#48]
Now that we have the ability to parse LookML in Python with [`lkml`](https://github.com/joshtemple/lkml), we have the ability to compare the differences in the parsed tree and only run Spectacles against those modified dimensions.

I'm imagining running `git diff --name-only $TARGET_BRANCH` to determine which files were changed (it doesn't look like Circle has a target branch environment variable in its context but it is a [highly requested issue](https://ideas.circleci.com/ideas/CCI-I-894)).

For each changed file, we would parse the LookML on the source and target branches and compare the resulting trees to understand which dimensions were changed.

Last, we would need a way to pass specific _dimensions_ to Spectacles via the model selector (might require changes to requirements in #21). Fonz then would query only the modified dimensions.

This could also interact with caching in #22. You might want to run the unchanged dimensions using the cached queries instead of rebuilding them.

**Comment by DylanBaker** [comment]
This all sounds good to me. 

> Last, we would need a way to pass specific dimensions to Fonz via the model selector (might require changes to requirements in #21). Fonz then would query only the modified dimensions.

I agree it might require some changes there. I can post comments on #21, but my gut feel is simply to extend the model selection with another '.'? i.e. model would be `model.*`, explore would be `model.explore.*` and dimension would be `model.explore.dimension`? It's possible that gets too verbose?

One thing I think we would probably need to do is also run any dimensions that reference the changed dimensions? I think we could also pull that from the parser?
