### ISSUE TITLE
Non-incremental runs with commit refs fail

### ISSUE THREAD

**Issue by joshtemple** [spectacles-ci/spectacles#522]
User reported this issue on Slack [[link to thread](https://spectacles-ci.slack.com/archives/CPXFRB17C/p1646240272181719)].

Spectacles is throwing an error about a non-ephemeral branch being used for a commit. Likely the logic in the runner is not correct for this sort of case.

**Comment by danneaves-ee** [comment]
Seeing this issue as well :+1:
