### ISSUE TITLE
Can't exclude Explores using Config file with the new Spectacles 2.X

### ISSUE THREAD

**Issue by mathieu-chiavassa** [spectacles-ci/spectacles#526]
Hi,
First of all, thanks a lot for your amazing work on Spectacles 2.X 🚀 
I have been trying to adapt my Looker repo to the recent Spectacles version, and I think I run into a problem trying to exclude specific explores from the tests.
I am using the `SQL Validator` and I want to pass the `explores` argument as part of my config.yml file. Since the `--exclude` arg was removed I need to do it using a leading hyphen for the explores that I want to exclude. I have been looking at your [documentation](https://docs.spectacles.dev/cli/reference/sql-validator/#explores) though all the examples are only using the command line.

Basically the problem that I encountered is the following:
From the command line this works perfectly and runs all explores in `model_a` excluding `explore_b`:
```
--explores "model_a/*" -model_a/explore_b
```
But the following code in config file still runs all explores in `model_a` and **does not exclude** the `explore_b`:
```
explores:
  - model_a/*
  - -model_a/explore_b
```

Very similar behaviour was observed with the following:
From the command line this works perfectly and runs all explores in all models except for `model_a/explore_b`:
```
--explores -model_a/explore_b
```
But the following code in config file does not run **anything** and gives me the `Testing 0 explores`:
```
explores:
  - -model_a/explore_b
```

Would this be related to the fact that hyphen is used in yaml to specify the elements of a list?
Or am I doing something wrong in my config file and in this case what should be the right syntax to exclude some specific explores from a model?

Sorry for bothering you, and thank you so much for your help! 🙂

**Comment by DylanBaker** [comment]
Hi @mathieu-chiavassa. Thank you for raising this!

Could you let me know what behaviour you see if you double quote like this:

```yaml
explores:
  - "-model_a/explore_b"
```

**Comment by mathieu-chiavassa** [comment]
Hi @DylanBaker thank you for your fast reply!

Same thing if I try the following it just gives me `Testing 0 explores` instead of all explores in all models except `explore_b`
```
explores:
  - "-model_a/explore_b"
```
And if I do this below, it runs for all the explores in `model_a` and does not exclude the `explore_b`
```
explores:
  - "model_a/*"
  - "-model_a/explore_b"
```

It works fine with the command line but since the repo contains many models and many explores I need to use the config file instead.

Thanks for helping!

**Comment by DylanBaker** [comment]
Thanks for testing that out. We'll need to dig into this and figure out what's going on. We'll update this ticket with our findings.

cc-ing @joshtemple for visibility.

**Comment by DylanBaker** [comment]
Oh. I think I've figured this out. 

@mathieu-chiavassa, could you please try:

```yaml
explores:
  - "~model_a/explore_b"
```

**Comment by mathieu-chiavassa** [comment]
Hey @DylanBaker ! Amazing, yes it works like that with `~` 🚀 
I'll close the issue.

Thank you so much for your time today it was really helpful !

**Comment by DylanBaker** [comment]
@mathieu-chiavassa Glad that sorted it! I'm actually going to leave the issue open as we'd like to make this work with just the dash in both setups.
