### ISSUE TITLE
Github Actions SQL Validator with OAuth connections

### ISSUE THREAD

**Issue by emcfarlane** [spectacles-ci/spectacles#568]
Running under github action: `spectacles sql --project project --branch cli --incremental`

Using BigQuery, connection is setup by looker using a service account. When running get the following error prefix with:
```
OAuth log in required.
```
The `lookml` and `content` work as intended. Permissions are set up via env vars. What's causing the issue?

**Comment by DylanBaker** [comment]
Hi @emcfarlane. Thanks for creating the ticket. 

It looks like Looker is expecting the user to have authenticated with OAuth instead of a service account.

Could you please sudo as the user you created and see if you're able to run queries as that user in the Looker UI?

**Comment by emcfarlane** [comment]
Find the issue on our side, we are in the process of moving tables to have an OAuth connection. Is there a way for spectacles to use the service account and looker to default to OAuth?

**Comment by DylanBaker** [comment]
I'm not sure there is a way to dynamically split which users use which method. 

I think what most people have done in this setup is to sudo as the Spectacles user to authenticate via OAuth. This would allow that user to use the permissions of the user who went through that process. 

Would that work for your setup?
