### ISSUE TITLE
SSL Certificate errors when running SQL validator

### ISSUE THREAD

**Issue by ronduursma** [spectacles-ci/spectacles#643]
Every time I run the SQL validator, I get this message at some point in the process:

error uploading: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

I do get results from the validation, but I'm concerned that these errors may be a reason why my tests are running very slow.

**Comment by DylanBaker** [comment]
Hi @ronduursma. Thanks for your message.

I'm not able to replicate this unfortunately so not totally clear what might be going on. 

I did find [this comment](https://github.com/segmentio/analytics-python/issues/142#issuecomment-429952026) on a relevant thread. It suggests some other python packages might need updating if you are using OS X. You can do so by running:

```
pip install pyopenssl ndg-httpsclient pyasn1 urllib3
```

All that said, I don't expect this to be affecting your run times. If you are getting the results from the validation, this call would be happening right at the end after that all finishes. I think my colleague Josh might be helping you with the runtime issues in our Slack, but if I can help there at all, please let me know.

**Comment by ronduursma** [comment]
Hi @DylanBaker, thanks for looking into this. Yes, your colleague Josh has been helping me with this and it turned out that if we turn off tracking (--do-not-track), all these timeouts and SSL certificate errors go away. With that, I am closing the issue. Thanks again!

**Comment by lalyndsighart** [comment]
Hi @ronduursma, thanks for finding the fix - are you able to please provide more detail on the --do-not-track option please? Thanks

**Comment by ronduursma** [comment]
Hi @lalyndsighart, the fix was suggested to be my Spectacles support. As I understand it, --do-not-track prevents spectacles from uploading (anonymized) analytical data back to their company.
