### ISSUE TITLE
Incorrect SQL test generated from Parameter with default_value

### ISSUE THREAD

**Issue by ronduursma** [spectacles-ci/spectacles#668]
I have a parameter like this:

parameter: timeframe_selector {
    view_label: "Current vs. Previous Period"
    label: "Timeframe"
    default_value: "Current Month"
    type: string

    allowed_value: {
      label: "Current Month"
      value: "month"
    }
    allowed_value: {
      label: "Current Quarter"
      value: "quarter"
    }
    allowed_value: {
      label: "Current Year"
      value: "year"
    }
  }

Then later the parameter will be used as follows:

DATEDIFF(
                day
                , date_trunc({% parameter timeframe_selector %}, current_date() )
                , current_date()
                )

Spectacles will generate a SQL test like this:

SELECT
    DATEDIFF(
                day
                , date_trunc('Current Month', current_date() )
                , current_date()
                )
'Current Month' is not a valid DATE_TRUNC parameter.

Looker would never generate this.  For the default parameter value of 'Current Month', 
it would substitute 'month', so that test case is not valid.

**Comment by joshtemple** [comment]
Hey @ronduursma, Spectacles doesn't set the parameter, so Looker will take the `default_value` for the parameter. In this case, your `default_value` is `Current Month`, which is what the Spectacles tests use.

If you change `default_value` to `month`, it should solve it for you.

**Comment by joshtemple** [comment]
@ronduursma please let me know if that doesn't solve this for you, but going to close out this issue for now.
