### ISSUE TITLE
Handling concurrent Fonz sessions

### ISSUE THREAD

**Issue by DylanBaker** [spectacles-ci/spectacles#7]
I've been thinking about how we handle concurrent Fonz sessions on the same project. There is, unfortunately, a slight issue with the current implementation:

Currently, Fonz switches to the provided branch as part of the login flow. It then conducts all the checks while working on that branch. If the CI for another branch kicks off while the first one is still running, it will change branches and the first Fonz session will also get changed. (It is not possible, as far as I can tell, to isolate the branch to a given API session. 

A solution we had discussed was having the first API user create and then delete a new user as part of every Fonz run. Having explored this, I don't think the Looker API is going to provide us with what we need. It seems that, on the `Users` endpoint, you can create a set of API3 credentials, but that those only the client ID and not the client secret are available through the API. We would need to grab both the ID and the secret for that implementation to be possible. 

A second solution would be to check that Fonz is on the correct branch before every call. Effectively, you could make a git checkout API call before every other API call. This makes it _more_ likely that you'll always be on the correct branch, but doesn't guarantee it (as the checkout call from another Fonz run could still intercede).

Ultimately, if we can't create users for each run, I think you need to make the runs aware to each other in some way and queue them up so that they don't conflict. I can't currently think of a good way to do that, without building some form of service that keeps track of state. (In reality, we could actually build a _possibly paid_ web client to do this for customers à la dbt Cloud. A conversation for another time.)

**Comment by joshtemple** [comment]
I went down a few dead ends trying to solve this and I can't come up with any creative solutions beyond what you described here.

It seems like the API is more or less duplicating the experience of a logged in user: it's impossible to checkout two branches at the same time. This is a Looker design decisions, and I don't see a workaround.

Here's an idea to solve the branch reliability issue:

1. We create a specific Looker user for Fonz, our worker
2. We set it up so the worker exits development mode when it's not currently in use and returns to the `production` workspace
3. Any time we kick off a new Fonz run, we check the workspace ID of the worker. If it's `production`, we know we're good to start. If not, we wait until the workspace is back to `production`, signaling that the worker is idle again

There's still a small chance for race conditions if you have 5 Fonz runs all waiting and checking the workspace ID, but increasing the wait time should decrease the risk. As an added safety check, we can validate the branch name via the API before each query, assuming it doesn't add too much overhead.

This doesn't enable concurrency, but it solves the concern of the git branch being switched in the middle of a run. I don't see any way to enable concurrency beyond creating more Looker users and adding them to some kind of pool of API credentials to be cycled through for an available worker.

**Comment by DylanBaker** [comment]
> This doesn't enable concurrency, but it solves the concern of the git branch being switched in the middle of a run. I don't see any way to enable concurrency beyond creating more Looker users and adding them to some kind of pool of API credentials to be cycled through for an available worker.

100% agree with this. And I don't _think_ that's something Fonz should handle. The feels more like something that should be left up to the end-user/business as part of their deployment?

> Any time we kick off a new Fonz run, we check the workspace ID of the worker. If it's production, we know we're good to start. If not, we wait until the workspace is back to production, signalling that the worker is idle again

Generally, I think your idea could work. I feel like implementing something like this maybe oversteps the bounds of what Fonz as a tool should provide? I think people are going to likely want to run it locally (as I was doing yesterday) as part of their individual development work-flow. I wouldn't want to impose of them that their user has to start in production. 

A small other issue is that if Fonz crashes and doesn't reset the session to production, the 'lock' never gets released, which is an issue. 

In some CI setups, you can limit concurrent runs, so, the more I think of it, I'm inclined to treat this as something out of scope for Fonz at the moment.
