### ISSUE TITLE
422 Response from Looker API

### ISSUE THREAD

**Issue by ronduursma** [spectacles-ci/spectacles#719]
I have a branch named 13950 in my project. When I run spectacles I get this:

$ spectacles sql --config-file looker_dev_config.yaml --project erx-corereports --explores star-schema/fill_data --port 9199  --do-not-track --branch 13950 --remote-reset -v
Authenticating to the Looker as client ID 'xxxxxxxxxxxxxxxxxxxxxx'
Checking Looker instance release version
Connected to Looker version 23.4.45 using Looker API 4.0
Setting up branch manager in project 'erx-corereports'

Setting Git state for project 'erx-corereports' @ 13950:
.. Getting the workspace in use by this session
.. Getting active branch for project 'erx-corereports'
.. The active branch is 'master'
.. Updating session to use the dev workspace
.. Getting the workspace in use by this session
.. Getting active branch for project 'erx-corereports'
.. The active branch is 'tmp_spectacles_2ee3b06a09'
.. Branching 'tmp_spectacles_b61768c44e' off '13950'. Afterwards, restoring to branch
     'master' in project 'erx-corereports'
.. Creating branch 'tmp_spectacles_b61768c44e' on project 'erx-corereports'
.. Hard resetting branch 'tmp_spectacles_b61768c44e' on project 'erx-corereports' to ref
     '13950'
Completed SQL validation in 2 seconds.

Couldn't update Git branch. Unable to update branch 'tmp_spectacles_b61768c44e' in project 'erx-corereports' using ref '13950'. Please try again.

Run in verbose mode (-v) or check your log file to see the full response from the Looker API. For support, please create an issue at https://github.com/spectacles-ci/spectacles/issues

.. Spectacles received a 422 response code from the Looker API with the following
     details: {
  "message": "Unable to resolve ref '13950'",
  "documentation_url": "ht
     tps://cloud.google.com/looker/docs/r/err/4.0/422/put/projects/:project_id/git_branc
     h"
}

The 13950 branch definitely exists in git.  This error does not occur with all branches. Some older ones work fine.

Any help appreciated!

**Comment by joshtemple** [comment]
Hey Ron!

There's a known issue with Looker 23.6 that was fixed in 23.6.77+ or 23.8.18+ that has been causing errors like this.

You can verify by Sudoing as the Spectacles Looker user, going into Development Mode, and attempting to check out the branch. You should get an error.

If that's the case, the easiest way to fix will be to delete the Spectacles Looker user and create a new one, then add the new Looker user's API credentials in Spectacles Settings > Workers (and delete the old one).

**Comment by ronduursma** [comment]
Hi Josh, thanks for the quick response!

I did the sudo, then it put me in the tmp_spectacles_b61768c44e branch, said it had uncommitted changes, I committed them, then I was able to switch to the 13950 branch.

Next, I tried running spectacles again and it worked this time!

Not sure if that makes sense to you, but I think I'll leave well enough alone.  Thanks again!
