### ISSUE TITLE
Spectacles connect fails because of incorrect httpx version installed

### ISSUE THREAD

**Issue by lakovicUros** [spectacles-ci/spectacles#728]
Since 11th of September our CLI spectacles tests are failing. Even though the httpx version specified in the requirements.txt file is 0.23.0, 0.25.0 gets installed instead.
https://pypi.org/project/httpx/#history

`ERROR: httpx 0.25.0 has requirement httpcore<0.19.0,>=0.18.0, but you'll have httpcore 0.15.0 which is incompatible.
Encountered unexpected TypeError: "__init__() got an unexpected keyword argument 'socket_options'"`

We solved the issue by changing commands to:
`pip install spectacles && pip install httpx==0.23.0`

Nevertheless, it would be great for this to be solved so we don't have to continue specifying httpx version in the future.

**Comment by joshtemple** [comment]
Should be resolved now as our current dependency for these libraries is:

```
httpx = "^0.26.0"
httpcore = ">=1.0.3"
```
