### ISSUE TITLE
AsyncConnectionPool - Error on ubuntu

### ISSUE THREAD

**Issue by jschintz-windriver** [spectacles-ci/spectacles#732]
The following error popped up this morning on ubutnu, and spectacles is not able to run

`Encountered unexpected TypeError: "AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'"`

**Comment by zephschafer** [comment]
My team started receiving this same error today

```
Encountered unexpected TypeError: "AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'"
```

**Comment by andrewrrandall** [comment]
We also started seeing the same error today. 
```
Encountered unexpected TypeError: "__init__() got an unexpected keyword argument 'socket_options'"
Full error traceback logged to file.

For support, please create an issue at https://github.com/spectacles-ci/spectacles/issues

Error: Process completed with exit code 1.
```

**Comment by DylanBaker** [comment]
Thanks all. We're having a look now. We think we've identified the problem and should hopefully have a release out soon.

**Comment by joshtemple** [comment]
Installing with version 2.3.16 should fix this issue.
