### ISSUE TITLE
TypeError: "AsyncConnectionPool.__init__() got an  unexpected keyword argument 'socket_options'"

### ISSUE THREAD

**Issue by alittlesliceoftom** [spectacles-ci/spectacles#734]
Version: 2.3.14. 

Run:
` spectacles connect --config-file config.yaml -v`

Return error: 
```
self._pool = httpcore.AsyncConnectionPool(
TypeError: AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'

Encountered unexpected TypeError: "AsyncConnectionPool.__init__() got an unexpected keyword argument 'socket_options'"
Full error traceback logged to file.
```

**Comment by alittlesliceoftom** [comment]
Pip list from venv: 

Package            Version
------------------ ---------
analytics-python   1.4.post1
anyio              3.7.1
backoff            1.10.0
certifi            2023.7.22
charset-normalizer 3.3.2
colorama           0.4.6
exceptiongroup     1.1.3
h11                0.12.0
httpcore           0.15.0
httpx              0.25.1
idna               3.4
monotonic          1.6
pip                23.0.1
pydantic           1.10.13
python-dateutil    2.8.2
PyYAML             6.0.1
requests           2.31.0
setuptools         65.5.0
six                1.16.0
sniffio            1.3.0
spectacles         2.3.14
tabulate           0.9.0
typing_extensions  4.8.0
urllib3            2.0.7

**Comment by alittlesliceoftom** [comment]
Note - the instructions state to use python 3.8, but i'm on 3.10: 

```pyenv virtualenv 3.8 spectacles && pyenv local spectacles```

 https://docs.spectacles.dev/cli/tutorials/getting-started/
 
 So that's almost certainly the issue, leaving this here pending me confirming that and to help anyone else who googles the same issue.

**Comment by DylanBaker** [comment]
Hey @alittlesliceoftom. I think this should be resolved in [the most recent release](https://github.com/spectacles-ci/spectacles/releases/tag/v2.3.16).
