### ISSUE TITLE
Encountered unexpected TypeError: "__init__() got an unexpected keyword argument 'socket_options'"

### ISSUE THREAD

**Issue by AnhVust** [spectacles-ci/spectacles#736]
Hi, we ran our Spectacles commands as belows:

`spectacles sql --config-file config.yaml --project studytube --explores abc/ef abc/dg --commit-ref "${SEMAPHORE_GIT_PR_SHA:-${SEMAPHORE_GIT_SHA}}"`

And received this error:

`Encountered unexpected TypeError: "__init__() got an unexpected keyword argument 'socket_options'"`

Not sure if there was anything that changed in the overall Spectacles commands?

**Comment by attrivivekFF** [comment]
@AnhVust Upgrading spectacles to latest version 2.3.16 fixed this error for us.
