### ISSUE TITLE
Unable to checkout Git branch

### ISSUE THREAD

**Issue by anhoa-vu** [spectacles-ci/spectacles#826]
My team encountered the issue below. Would appreciate any suggestions for how to resolve this error!

```
Authenticating to the Looker as client ID '*****'
Checking Looker instance release version
Connected to Looker version 24.16.29 using Looker API 4.0
Setting up branch manager in project '******'

Setting Git state for project '******' @ staging:
.. Getting the workspace in use by this session
.. Getting active branch for project '*******'
.. The active branch is '*****'
.. Updating session to use the dev workspace
.. Setting project '*******' branch to 'staging'
Completed content validation in 7 seconds.


Couldn't checkout Git branch. Unable to checkout Git branch 'staging'. If you have uncommitted changes on the current branch, please commit or revert them, then try again.

.. Spectacles received a 422 response code from the Looker API with the following
     details: {
  "message": "JGIT Checkout Branch failed: Checkout conflict with files:
......
}
```

**Comment by DylanBaker** [comment]
Hi @anhoa-vu. Could I please ask you to sudo as the Looker user you are using, go into development mode, and try to checkout a new branch? I expect we will see an issue there that will highlight what is going on. Often, resetting the git connection in Looker solves this. You can also [solve it by re-creating the user](https://docs.spectacles.dev/app/guides/fix-looker-git-error/).

**Comment by anhoa-vu** [comment]
Thanks, @DylanBaker. This is very helpful!

**Comment by nianglao** [comment]
I also met the checkout error 
`Couldn't checkout Git branch. Unable to checkout Git branch 'staging'. If you have uncommitted changes on the current branch, please commit or revert them, then try again.

.. Spectacles received a 500 response code from the Looker API with the following`

Re-creating the user can't solve my issue.

I found I can't swith branch in Looker Development mode, with error `Uh oh! Something went wrong.`

I followed the wiki   [Troubleshooting guide to git related issue for om premise]( https://www.googlecloudcommunity.com/gc/The-Kitchen-Table/Troubleshooting-guide-to-git-related-issue-for-on-premise/m-p/690765), and found below 
`sh-5.2# git status
fatal: detected dubious ownership in repository at '/opt/looker/shared_models/models/xxx'
To add an exception for this directory, call:

	git config --global --add safe.directory /opt/looker/shared_models/models/xxx`
Then I followed the  https://stackoverflow.com/questions/72978485/git-submodule-update-failed-with-fatal-detected-dubious-ownership-in-reposit execute `git config --global --add safe.directory '*'` 

And finnaly git checkout works and Spectacles can use --branch parameter.
