### ISSUE TITLE
Change SQL batch default to True

### ISSUE THREAD

**Issue by joshtemple** [spectacles-ci/spectacles#83]
We should change the default value of `batch` to True so people don't overwhelm their instances accidentally.

**Comment by msandt3** [comment]
I just did this playing with the tool. Would love to see it

**Comment by DylanBaker** [comment]
@msandt3 We will definitely get this merged in shortly. I'm super curious how you discovered the tool?

**Comment by msandt3** [comment]
I'm actually going to be at Join and saw the talk on the agenda.

I've been looking to get some level of CI and automated testing in place
for our looker team for a while. Just googling around dropped me here.
