### ISSUE TITLE
Pull updated changes from remote after checkout

### ISSUE THREAD

**Issue by joshtemple** [spectacles-ci/spectacles#89]
Currently, spectacles does not pull changes from remote if the local branch is behind the remote branch. This is a problem if the user making changes to the branch is different than the user running spectacles (e.g. a bot user set up for the sole purpose of running spectacles queries). In that case, the spectacles bot user would not have the most recent changes unless it had some way of pulling them from remote.

There is a way to [reset to remote via the API](https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/project#reset_to_remote), but will delete any saved or committed changes

However, spectacles can determine the [number of commits](https://docs.looker.com/reference/api-and-integration/api-reference/v3.1/project#get_active_git_branch) it is ahead and behind the remote. We may be able to do some kind of checking to anticipate if commits would be deleted and fail with an error message or something. This would avoid resetting commits not pushed to remote, but probably wouldn't work for things that are saved by not committed.

**Comment by joshtemple** [comment]
Did some testing on this. Reset to remote does revert saved but uncommitted changes. There does not seem to be a way to detect the existence of saved but uncommitted changes on the current branch.

**Comment by msandt3** [comment]
👍 for this one as well. Spectacles rocks btw :)
